### ISSUE TITLE
PHP notice on the BuddyMeet page

### ISSUE THREAD

**Issue by truongwp** [tdakanalis/buddymeet#1]
I got this notice on the BuddyMeet page. It's a fresh installation. I install BuddyPress and BuddyMeet, enable group function and create a group then go the BuddyMeet page of the group.

`Notice: Trying to get property 'group' of non-object in /srv/www/wp-quiz-pro.mts/public_html/wp-content/plugins/buddymeet/includes/buddymeet-component-class.php on line 100`

**Comment by tdakanalis** [comment]
This has been fixed.
